language: android
sudo: required

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
    - ./gradlew clean build connectedCheck
