language: android
sudo: required
jdk: oraclejdk8
os:
    - linux

android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - tools
    - extra-android-m2repository
    - extra-google-android-support

    - android-16
    - android-21
    - android-22
    - android-25

    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

before_install:
    - chmod +x gradlew

script:
    - ./gradlew build connectedCheck